version: '3'

services:

  db:
    image: postgres
    container_name: messenger-postgres
    environment:
      POSTGRES_USER: ${ADMIN}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - messenger-network

  redis:
    image: redis
    container_name: messenger-redis
    ports:
      - "6379:6379"
    depends_on:
      - db
    restart: always
    networks:
      - messenger-network

  web:
    build: .
    container_name: messenger
    command: bash -c "uvicorn --workers 4 settings.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "192.168.0.101:8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always
    networks:
      - messenger-network


networks:
  messenger-network: